/*
	Popup
	Send a Hug Component
  ---------------------------------------------------
  MIT License

  Copyright (c) 2020-2024 Send A Hug

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  The provided Software is separate from the idea behind its website. The Send A Hug
  website and its underlying design and ideas are owned by Send A Hug group and
  may not be sold, sub-licensed or distributed in any way. The Software itself may
  be adapted for any purpose and used freely under the given conditions.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
*/

// Angular imports
import { Component, Output, EventEmitter, input, computed, inject } from "@angular/core";
import { tap } from "rxjs";
import { CommonModule } from "@angular/common";

// App-related import
import { ApiClientService } from "@app/services/apiClient.service";
import { SWManager } from "@app/services/sWManager.service";
import { AlertsService } from "@app/services/alerts.service";
import { PopUpComponent } from "@common/popUp/popUp.component";
import { TeleportDirective } from "@app/directives/teleport.directive";
import { IdbStoreType } from "@app/interfaces/types";
import { ReportData } from "@app/interfaces/report.interface";

@Component({
  selector: "item-delete-form",
  templateUrl: "./itemDeleteForm.component.html",
  standalone: true,
  imports: [CommonModule, PopUpComponent, TeleportDirective],
})
export class ItemDeleteFormComponent {
  private apiClient = inject(ApiClientService);
  private swManager = inject(SWManager);
  private alertsService = inject(AlertsService);
  // indicates whether edit/delete mode is still required
  @Output() editMode = new EventEmitter<boolean>();
  @Output() deleted = new EventEmitter<number>();
  readonly reportData = input<ReportData | undefined>();
  readonly deleteEndpoint = input<string | undefined>();
  readonly itemType = input<"Post" | "Message" | "Thread" | undefined>();
  readonly itemId = input<number | undefined>();
  readonly bulkDelete = input<boolean>(false);
  readonly isAdmin = input<boolean>(false);
  readonly fullDeleteUrl = computed(() =>
    this.bulkDelete() ? this.deleteEndpoint() : `${this.deleteEndpoint()}/${this.itemId()}`,
  );

  /**
   * Deletes a single item or multiple items.
   * @returns a subscription generated by subscribing to the APIClient observable.
   */
  deleteItem() {
    if (!this.deleteEndpoint()) return;

    return this.apiClient
      .delete<{ success: boolean; userID?: number; deleted: number }>(this.fullDeleteUrl()!)
      .pipe(
        tap((response) => {
          if (this.isAdmin()) return;

          const successAlertMessage = this.bulkDelete()
            ? `${response.deleted} ${this.itemType()?.toLowerCase()}s were deleted.`
            : `${this.itemType()} ${response.deleted} was deleted.`;
          this.alertsService.createSuccessAlert(successAlertMessage);
        }),
      )
      .subscribe({
        next: (response) => {
          if (!this.bulkDelete()) {
            // delete the item from idb
            this.swManager.deleteItem(
              `${this.itemType()!.toLowerCase()}s` as IdbStoreType,
              response.deleted,
            );
          }

          this.deleted.emit(response.deleted);
          this.editMode.emit(false);
        },
      });
  }
}
