/*
	Popup
	Send a Hug Component
  ---------------------------------------------------
  MIT License

  Copyright (c) 2020-2024 Send A Hug

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  The provided Software is separate from the idea behind its website. The Send A Hug
  website and its underlying design and ideas are owned by Send A Hug group and
  may not be sold, sub-licensed or distributed in any way. The Software itself may
  be adapted for any purpose and used freely under the given conditions.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
*/

// Angular imports
import { Component, Output, EventEmitter, input } from "@angular/core";
import { tap } from "rxjs";
import { CommonModule } from "@angular/common";

// App-related import
import { AdminService } from "@app/services/admin.service";
import { ApiClientService } from "@app/services/apiClient.service";
import { SWManager } from "@app/services/sWManager.service";
import { AlertsService } from "@app/services/alerts.service";
import { PopUpComponent } from "@common/popUp/popUp.component";
import { TeleportDirective } from "@app/directives/teleport.directive";
import { IdbStoreType } from "@app/interfaces/types";
import { ReportData } from "@app/interfaces/report.interface";

@Component({
  selector: "item-delete-form",
  templateUrl: "./itemDeleteForm.component.html",
  standalone: true,
  imports: [CommonModule, PopUpComponent, TeleportDirective],
})
export class ItemDeleteFormComponent {
  // indicates whether edit/delete mode is still required
  @Output() editMode = new EventEmitter<boolean>();
  @Output() deleted = new EventEmitter<number>();
  readonly reportData = input<ReportData | undefined>();
  // New inputs
  readonly deleteEndpoint = input<string | undefined>();
  readonly itemType = input<"Post" | "Message" | "Thread" | undefined>();
  readonly itemId = input<number | undefined>();
  readonly bulkDelete = input<boolean>(false);

  // CTOR
  constructor(
    private adminService: AdminService,
    private apiClient: ApiClientService,
    private swManager: SWManager,
    private alertsService: AlertsService,
  ) {}

  /*
  Function Name: deleteItem()
  Function Description: Sends a request to delete a post or a message to the items service.
  Parameters: None.
  ----------------
  Programmer: Shir Bar Lev.
  */
  deleteItem() {
    // if it's a single item, make the request to delete it
    if (this.bulkDelete() === false) {
      this.deleteSingleItem();
    }
    // if the user is attempting to delete all of the user's posts/messages
    else if (this.bulkDelete() === true) {
      this.deleteMultipleItems();
    }
  }

  /**
   * Deletes a single item (be it a post, a message or a thread).
   * @returns a subscription generated by subscribing to the request observable.
   */
  deleteSingleItem() {
    if (!this.deleteEndpoint() || !this.itemId()) return;

    return this.apiClient
      .delete<{ success: boolean; deleted: number }>(`${this.deleteEndpoint()!}/${this.itemId()!}`)
      .pipe(
        tap((response) =>
          this.alertsService.createSuccessAlert(
            `${this.itemType()} ${response.deleted} was deleted.`,
          ),
        ),
      )
      .subscribe({
        next: (response) => {
          // delete the item from idb
          this.swManager.deleteItem(
            `${this.itemType()!.toLowerCase()}s` as IdbStoreType,
            response.deleted,
          );

          this.deleted.emit(response.deleted);
          this.editMode.emit(false);
        },
      });
  }

  /*
  Function Name: deletePost()
  Function Description: Sends a request to the admin service to delete a post and
                        dismiss the report (if selected by the user).
  Parameters: closeReport (boolean) - whether or not to close the report.
  ----------------
  Programmer: Shir Bar Lev.
  */
  deletePost(closeReport: boolean) {
    if (!this.reportData()) return;

    this.adminService.deletePost(this.itemId()!, this.reportData()!, closeReport).add(() => {
      this.deleted.emit(this.itemId());
      this.editMode.emit(false);
    });
  }

  /**
   * Deletes multiple items.
   * @returns an observable of the response.
   */
  deleteMultipleItems() {
    if (!this.deleteEndpoint() || !this.itemId()) return;

    return this.apiClient
      .delete<{ success: boolean; userID: number; deleted: number }>(this.deleteEndpoint()!)
      .pipe(
        tap((response) =>
          this.alertsService.createSuccessAlert(
            `${response.deleted} ${this.itemType()?.toLowerCase()}s were deleted.`,
          ),
        ),
      )
      .subscribe({
        next: (response) => {
          this.deleted.emit(response.userID);
          this.editMode.emit(false);
        },
      });
  }
}
