dist: bionic

language: node_js
node_js:
  - "14"

addons:
  chrome: stable

cache:
  directories:
     - ./node_modules

install:
  - sudo -E npm install
  - sudo -E npm install -g gulp-cli

script:
  - sudo -E gulp unitTest --max_old_space_size=8192
