dist: bionic

language: node_js
node_js:
  - "12"

addons:
  chrome: stable

services:
  - xvfb

cache:
  directories:
     - ./node_modules

install:
  - npm install
  - npm install -g gulp-cli

script:
  - sudo -E env "PATH=$PATH" gulp unitTest --max_old_space_size=8192
