dist: trusty
sudo: true

language: node_js
node_js:
  - "12"

addons:
  chrome: beta

cache:
  directories:
     - ./node_modules

install:
  - npm install
  - npm install -g gulp-cli

script:
  - gulp unitTest --max_old_space_size=8192
