dist: bionic

language: node_js
node_js:
  - "14"

addons:
  chrome: stable

cache:
  directories:
     - ./node_modules

install:
  - npm install
  - npm install -g gulp-cli

script:
  - build/update-linux-sandbox.sh
  - gulp unitTest --max_old_space_size=8192
