dist: trusty
sudo: true

language: node_js
node_js:
  - "12"

addons:
  chrome: stable

cache:
  directories:
     - ./node_modules

install:
  - npm install
  - npm install -g gulp-cli

before_script:
  - CHROME_MAIN_VERSION=`google-chrome-stable --version | sed -E 's/(^Google Chrome |\.[0-9]+ )//g'`
  - CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAIN_VERSION"`
  - curl "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin

script:
  - gulp unitTest --max_old_space_size=8192
