version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    environment:
      CHROME_BIN: /usr/bin/google-chrome
    steps:
      - checkout
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - run: npm install -g gulp
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: gulp test -- --no-watch --no-progress --browsers=ChromeHeadlessCI