version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.8
  cypress: cypress-io/cypress@3.3.1
  codecov: codecov/codecov@4.1.0
jobs:
  format:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          key: send-hug-v1-
      - run: npm install
      - save_cache:
          key: send-hug-v1-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npx prettier --check .
  test:
    docker:
      - image: cimg/node:lts-browsers
    environment:
      CHROME_BIN: /usr/bin/google-chrome
    steps:
      - checkout
      - run: sudo apt-get update
      - browser-tools/install-browser-tools
      - run: google-chrome --version
      - restore_cache:
          key: send-hug-v1-
      - run: npm install
      - save_cache:
          key: send-hug-v1-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npx playwright install-deps
      - run: npx playwright install
      - run: npm test
      - codecov/upload
  e2e:
    docker:
      - image: cimg/python:3.11-node
        environment:
          DATABASE_URL: postgresql+asyncpg://postgres:password@localhost:5432/test_sah
          BASE_DATABASE_URL: postgresql://postgres:password@localhost:5432/test_sah
          QUART_APP: send-hug-backend/app.py:app
          FLASK_ENV: development
          FRONTEND: http://localhost:3000
          FIREBASE_CREDENTIALS_FILE: send-hug-backend/test_creds.json
      - image: cimg/postgres:14.10
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: test_sah
          POSTGRES_PASSWORD: password
    environment:
      CHROME_BIN: /usr/bin/google-chrome
    steps:
      - checkout
      - run: |
          sudo npm install -g pa11y-ci --unsafe-perm=true --allow-root
          sudo apt-get update
          sudo apt-get install -y postgresql-client python3-pip xvfb
      - run: |
          cd ..
          git clone https://github.com/sendahug/send-hug-backend
      - run:
          name: Install Python deps
          command: |
            cd ..
            pip3 install -r send-hug-backend/requirements.txt
            python3 -m pip install --upgrade pip
      # Dockerize installation to wait for the database to load
      # Taken from: https://support.circleci.com/hc/en-us/articles/360006773953-Race-Conditions-Wait-For-Database
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: psql -d $BASE_DATABASE_URL -c "CREATE ROLE circleci WITH SUPERUSER, LOGIN;"
      - run:
          name: Restore database
          command: |
            mv e2e/setup.py ../send-hug-backend
            echo "$FIREBASE_TEST_ACCT_KEY" > ../send-hug-backend/test_creds.json
            cd ../send-hug-backend
            python3 setup.py
      - run:
          name: Start backend
          command: |
            cd ..
            quart run
          background: true
      - browser-tools/install-browser-tools
      - run: google-chrome --version
      - cypress/install
      - restore_cache:
          key: send-hug-v1-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: send-hug-v1-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: Start frontend server
          command: npm run dev
          background: true
      - run:
          name: Run e2e tests
          command: npm run cypress
  accessibility:
    docker:
      - image: cimg/python:3.11-node
        environment:
          DATABASE_URL: postgresql+asyncpg://postgres:password@localhost:5432/test_sah?sslmode=disable
          QUART_APP: send-hug-backend/app.py:app
          FLASK_ENV: development
          FRONTEND: http://localhost:3000
          FIREBASE_CREDENTIALS_FILE: send-hug-backend/test_creds.json
      - image: cimg/postgres:14.10
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: test_sah
          POSTGRES_PASSWORD: password
    environment:
      CHROME_BIN: /usr/bin/google-chrome
    steps:
      - checkout
      - run: |
          sudo npm install -g pa11y-ci --unsafe-perm=true --allow-root
          sudo apt-get update
          sudo apt-get install -y postgresql-client python3-pip xvfb
      - run: |
          cd ..
          git clone https://github.com/sendahug/send-hug-backend
      - run:
          name: Install Python deps
          command: |
            cd ..
            pip3 install -r send-hug-backend/requirements.txt
            python3 -m pip install --upgrade pip
      # Dockerize installation to wait for the database to load
      # Taken from: https://support.circleci.com/hc/en-us/articles/360006773953-Race-Conditions-Wait-For-Database
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Restore database
          command: |
            mv e2e/setup.py ../send-hug-backend
            echo "$FIREBASE_TEST_ACCT_KEY" > ../send-hug-backend/test_creds.json
            cd ../send-hug-backend
            python3 setup.py
      - run:
          name: Start backend
          command: |
            cd ..
            quart run
          background: true
      - browser-tools/install-browser-tools
      - run: google-chrome --version
      - restore_cache:
          key: send-hug-v1-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: send-hug-v1-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: Start frontend server
          command: npm run dev
          background: true
      - run: sleep 15
      - run:
          name: Run accessibility tests
          command: pa11y-ci --sitemap http://localhost:3000/sitemap.xml --config .pa11yci

workflows:
  run-testing:
    jobs:
      - format
      - test
      - e2e
      - accessibility
