version: 2
jobs:
  build:
    working_directory: ~/my-project
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run: npm set prefix=/home/circleci/npm && echo 'export PATH=$HOME/circleci/npm/bin:$PATH' >> /home/circleci/.bashrc
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm install --global gulp-cli
      - run: npm test --max_old_space_size=8192
