name: Add issues/PRs to project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
    branches:
      - dev
      - live
  pull_request_target:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    # If the PR is coming from a fork (pull_request_target), ensure it's opened by "dependabot[bot]".
    # Otherwise, clone it normally.
    # From here: https://hugo.alliau.me/2021/05/04/migration-to-github-native-dependabot-solutions-for-auto-merge-and-action-secrets/#share-your-secrets-with-dependabot
    if: |
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
      (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
    steps:
      - uses: actions/add-to-project@v0.6.1
        with:
          # You can target a project in a different organization
          # to the issue
          project-url: https://github.com/orgs/sendahug/projects/7
          github-token: ${{ secrets.ISSUES_PRS_PAT }}
