name: "Pull Request Labeler"
on:
  pull_request:
    branches: ["dev"]

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:
          configuration-path: ".github/labeler.yml"
          sync-labels: true
