name: Update Changelog

on:
  push:
    branches: [dev]

jobs:
  update_changelog:
    uses: sendahug/send-a-workflow/.github/workflows/updatechangelog.yml@main
    with:
      base_repo_url: "https://github.com/sendahug/send-hug-frontend"
      repository: "send-hug-frontend"
    secrets: inherit
