# Update the superproject repo's submodules
name: Update Superproject

on:
  push:
    branches: [live]

jobs:
  build:
    # Use the reusable workflow
    uses: sendahug/send-a-workflow/.github/workflows/update_superproject.yml@main
    with:
      branch: "live"
    secrets: inherit
