name: Update Superproject

# Controls when the action will run.
on:
  # Triggers the workflow on push events for the Dev branch
  push:
    branches: [live, change/move_to_reusable_workflows]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    uses: sendahug/send-a-workflow/.github/workflows/update_superproject.yml@feature/initial_workflows
    with:
      branch: "test"
