name: Update Superproject

# Controls when the action will run. 
on:
  # Triggers the workflow on push events for the Dev branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 
      - name: Clone superproject repo
        run: git clone --recursive https://github.com/sendahug/sendahug
      
      - name: Update frontend
        run: |
          cd sendahug
          cd send-hug-frontend
          git checkout master
          git pull origin master
          
      - run: cd ..
      
      - name: Commit & push updates
        run: |
          if [ -n "$(git status --porcelain)" ];
          then
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git add .
            git commit -m 'Updated frontend submodule.'
            git push
          fi
