# Update the superproject repo's submodules
name: Update Superproject

on:
  push:
    branches: [live, change/move_to_reusable_workflows]

jobs:
  build:
    # Use the reusable workflow
    uses: sendahug/send-a-workflow/.github/workflows/update_superproject.yml@feature/initial_workflows
    with:
      branch: "dev"
    secrets: inherit
