name: Update Superproject

# Controls when the action will run.
on:
  # Triggers the workflow on push events for the Dev branch
  push:
    branches: [live, change/move_to_reusable_workflows]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      uses: sendahug/send-a-workflow/.github/workflows/update_superproject.yml@feature/initial_workflows
      with:
        branch: "test"

            git add .
            git commit -m 'Updated frontend submodule.'
            git push
          fi
